[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    X-Content-Type-Options = "nosniff"
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
